[project]
name = "enterprise-agent-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "cohere>=7.0.8",
    "fastapi>=0.141.1",
    "instructor>=1.15.4",
    "langchain>=1.3.15",
    "langgraph-checkpoint-postgres>=3.1.2",
    "litellm>=1.97.0",
    "openapi>=2.0.0",
    "pandas>=3.0.5",
    "psycopg>=3.3.4",
    "psycopg-binary>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "qdrant-client>=1.19.0",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.61.1",
    "tiktoken>=0.13.0",
    "tqdm>=4.70.0",
]
