"""create shopping cart items and inventory

Revision ID: ac9d475e19f3
Revises: 
Create Date: 2026-08-17 17:57:35.558018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9d475e19f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS shopping_carts")
    op.execute("CREATE SCHEMA IF NOT EXISTS warehouses")
    op.create_table('shopping_cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('shopping_cart_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_image_url', sa.String(length=1000), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('price >= 0', name='positive_price'),
    sa.CheckConstraint('quantity > 0', name='positive_quantity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shopping_cart_id', 'product_id', name='unique_user_cart_product'),
    schema='shopping_carts'
    )
    op.create_index(op.f('ix_shopping_carts_shopping_cart_items_product_id'), 'shopping_cart_items', ['product_id'], unique=False, schema='shopping_carts')
    op.create_index(op.f('ix_shopping_carts_shopping_cart_items_user_id'), 'shopping_cart_items', ['user_id'], unique=False, schema='shopping_carts')
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), sa.Computed('total_quantity - reserved_quantity', persisted=True), nullable=False),
    sa.Column('warehouse_location', sa.String(length=255), nullable=True),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True),
    sa.Column('estimated_processing_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('reserved_quantity <= total_quantity', name='valid_reservation'),
    sa.CheckConstraint('reserved_quantity >= 0', name='positive_reserved_quantity'),
    sa.CheckConstraint('total_quantity >= 0', name='positive_total_quantity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='unique_warehouse_product'),
    schema='warehouses'
    )
    op.create_index('idx_inventory_product', 'inventory', ['product_id'], unique=False, schema='warehouses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory_product', table_name='inventory', schema='warehouses')
    op.drop_table('inventory', schema='warehouses')
    op.drop_index(op.f('ix_shopping_carts_shopping_cart_items_user_id'), table_name='shopping_cart_items', schema='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_shopping_cart_items_product_id'), table_name='shopping_cart_items', schema='shopping_carts')
    op.drop_table('shopping_cart_items', schema='shopping_carts')
    # ### end Alembic commands ###
